# Site Settings
title: Chun Ming Chang
url: 'http://nothinghard.github.io'
baseurl: '/online_cv/' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Chun Ming Chang
tagline: EECS PhD student
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Summarise your career here lorem ipsum dolor sit amet, consectetuer adipiscing elit.
You can <a href="#" target="_blank">download this free resume/CV template here</a>. Aenean
commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient
montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu.'

#sidebar links
email: d05921027@ntu.edu.tw
phone: +886 911 093 825
website: nothinghard.github.io #do not add http://
linkedin: 
github: nothinghard
twitter: '@twcmchang'
#Update all the sections by editing the files inside _data folder.

# Tracker
# analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
