# Site Settings
title: Chun Ming Chang
url: 'http://nothinghard.github.io'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Chun Ming Chang
tagline: EECS PhD student
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I am currently a research assistant in 
<a href="http://dirl.iis.sinica.edu.tw/" target="_blank">Data Insight Research Lab</a> of Academia Sinica, 
and also a first year Ph.D. student in Electrical Engineering and Computer Science (EECS) in National Taiwan University, 
working with Dr. Sheng-Wei (a.k.a. Kuan-Ta) Chen and Dr. Chin-Laung Lei. 
My research focuses on Deep Learning and its applications, especially in medical imageology.<br>

In addition to my research experience, I am one of the invited speakers to introduce machine learning and deep learning 
in both theoretical and practical aspects in <a href="http://ds.sinica.edu.tw/ai-month-2017/">AI Month 2017</a> and 
[ML Month 2017](http://ds.sinica.edu.tw/category/2017-ml-month/), Academia Sinica. 
Moreover, I also give a <a href="http://foundation.datasci.tw/step-by-step-dl-170813/">hands-on tutorial of deep learning</a> and 
a [hands-on tutorial of practical data analysis in R]() in <a href="http://foundation.datasci.tw/">Data Science Conference in Taiwan</a>. <br>
See my <a href="https://nothinghard.github.io/online-cv/">CV</a> for more details.'

#sidebar links
email: d05921027@ntu.edu.tw
phone: +886 911 093 825
website: nothinghard.github.io #do not add http://
linkedin: 
github: nothinghard
twitter: '@twcmchang'
#Update all the sections by editing the files inside _data folder.

# Tracker
# analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
