# Site Settings
title: Chun Ming Chang
url: 'http://twcmchang.github.io'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Chun Ming Chang
tagline: NTU EECS PhD student
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: '<p> I am a first-year Ph.D. student in Electrical Engineering and Computer Science (EECS) 
in National Taiwan University, working with Dr. Sheng-Wei (Kuan-Ta) Chen and Dr. Chin-Laung Lei;
also a machine learning engineer in 
<a href="http://dirl.iis.sinica.edu.tw/">Data Insight Research Lab</a> of Academia Sinica.

<p> My research focuses on <font color="#fb8072">deep learning</font>, 
particularly in <font color="#fb8072">model compression</font> and <font color="#fb8072">energy-efficient inference</font>, and its applications in clinical diagnosis. 
To know more about my research, please find my <a href="https://twcmchang.github.io/publications/">publications</a> and <a href="https://twcmchang.github.io/projects/">projects</a>.

<p> Recently, I am honored to be one of the invited speakers of two distinguished lectures in Academia Sinica, AI Month and ML Month 2017. 
And also invited to give two hands-on tutorial sessions: <a href="https://www.slideshare.net/ssuser950871/handson-tutorial-of-deep-learning">deep learning in Python (slideshare)</a> and 
<a href="https://www.slideshare.net/ssuser950871/practical-data-analysis-in-r">practical data analysis in R (slideshare)</a> 
in Data Science Conference in Taiwan.'

#sidebar links
email: d05921027@ntu.edu.tw
phone: +886 911 093 825
website: twcmchang.github.io #do not add http://
linkedin: chun-min-chang
github: twcmchang
twitter: 'twcmchang'
#Update all the sections by editing the files inside _data folder.

# Tracker
# analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
